FROM ubuntu:18.04

RUN apt-get update \
      && apt-get install -y \
           build-essential \
           gfortran \
           git \
           wget

RUN apt-get clean all \
      && rm -r /var/lib/apt/lists/*
