ARG OS_VERSION="18.04"
FROM ubuntu:$OS_VERSION

RUN apt-get update \
      && apt-get install -y \
           build-essential \
           gfortran \
           git \
           wget \
      && apt-get clean all \
      && rm -r /var/lib/apt/lists/*
